# Generated by Django 5.1 on 2024-11-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_pessoa_pes_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
