# Generated by Django 5.1 on 2024-11-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_pessoa_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='EMP_NOVO',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
