# Generated by Django 5.1 on 2024-11-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_pessoatoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoatoken',
            name='PST_DATA_EXPIRACAO',
            field=models.DateTimeField(),
        ),
    ]
