# Generated by Django 5.1 on 2024-11-16 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_pessoatoken_pst_data_expiracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAuditoria',
            fields=[
                ('la_cod', models.AutoField(primary_key=True, serialize=False)),
                ('la_data_ultima', models.DateTimeField()),
                ('emp_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empresa')),
                ('pes_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Login_Auditoria',
            },
        ),
    ]
