# Generated by Django 5.1 on 2024-11-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_loginauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='PES_ADMINISTRADOR',
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
    ]
