# Generated by Django 5.1 on 2024-11-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_pessoa_pes_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='PES_FOTO_REFERENCIA',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='PES_FOTO_URL',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
