# Generated by Django 5.1 on 2024-12-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_pessoa_pes_foto_referencia_pessoa_pes_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='PES_CADASTRO_COMPLETO',
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='PES_TOKEN',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
