# Generated by Django 5.1 on 2024-12-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_pessoa_pes_cadastro_completo_pessoa_pes_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='PES_FOTO_URL',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
