# Generated by Django 5.1.2 on 2024-11-03 19:56

import datetime
import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('CARGO_COD', models.AutoField(primary_key=True, serialize=False)),
                ('CARGO_NOME', models.CharField(max_length=60, unique=True)),
                ('CARGO_DT_ATUALIZACAO', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaHoras',
            fields=[
                ('CTH_COD', models.AutoField(primary_key=True, serialize=False)),
                ('CTH_NOME', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('PRI_COD', models.AutoField(primary_key=True, serialize=False)),
                ('PRI_NOME', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('CLI_COD', models.AutoField(primary_key=True, serialize=False)),
                ('CLI_NOME', models.CharField(max_length=50)),
                ('CLI_RAMO_ATUACAO', models.CharField(blank=True, max_length=50, null=True)),
                ('CLI_CNPJ', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('EMP_COD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaInfo',
            fields=[
                ('EMI_COD', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_QUANTIDADE_FUNC', models.IntegerField()),
                ('EMP_OBJETIVO', models.CharField(blank=True, max_length=100, null=True)),
                ('DATA_CRIACAO', models.DateTimeField(auto_now_add=True)),
                ('EMP_COD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('FUN_COD', models.AutoField(primary_key=True, serialize=False)),
                ('FUNC_DT_CADASTRO', models.DateTimeField(default=datetime.datetime.now)),
                ('FUN_MAXIMO_HORAS', models.IntegerField()),
                ('FUN_VALOR_HORA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EMP_COD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empresa')),
                ('FUN_ROLES', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.cargo')),
                ('PES_COD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('HRO_COD', models.AutoField(primary_key=True, serialize=False)),
                ('HRO_OBSERVACAO', models.CharField(max_length=150)),
                ('HRO_CATEGORIA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.categoriahoras')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('PJT_COD', models.AutoField(primary_key=True, serialize=False)),
                ('PJT_NOME', models.CharField(max_length=150)),
                ('CLI_COD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('TRF_COD', models.AutoField(primary_key=True, serialize=False)),
                ('TRF_TITULO', models.CharField(max_length=200)),
                ('TRF_STATUS', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluída'), ('A', 'Atrasada')], max_length=10)),
                ('TRF_DATA_PRAZO', models.DateField()),
                ('PES_COD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.pessoa')),
                ('PJT_COD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.projeto')),
                ('TRF_PRIORIDADE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.prioridade')),
            ],
        ),
    ]
