# Generated by Django 5.1 on 2024-11-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='TRF_DATA_PRAZO',
        ),
        migrations.AddField(
            model_name='tarefas',
            name='TRF_DATA_CONCLUSAO',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
