# Generated by Django 5.1 on 2024-11-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_remove_tarefas_trf_data_prazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='TRF_DATA_CRIACAO',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
