# Generated by Django 5.1 on 2024-11-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_horastarefasvi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horas_trabalhadas',
            name='HRT_DT_FIM',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
