# Generated by Django 5.1 on 2024-11-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='FUN_MAXIMO_HORAS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='FUN_VALOR_HORA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
