# Generated by Django 5.1 on 2024-11-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_tarefas_trf_data_criacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysDetalhesTarefasVi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=200)),
                ('nome_cliente', models.CharField(max_length=50)),
                ('prioridade', models.CharField(max_length=50)),
                ('total_horas_trabalhadas', models.TimeField()),
                ('trf_data_conclusao', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=9)),
                ('trf_data_criacao', models.CharField(max_length=10)),
                ('trf_status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'sys_detalhes_tarefas_vi',
                'managed': False,
            },
        ),
    ]
