# Generated by Django 5.1 on 2024-11-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_alter_funcionario_fun_maximo_horas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresainfo',
            old_name='EMP_OBJETIVO',
            new_name='EMP_RAMO_ATUACAO',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='CLI_RAMO_ATUACAO',
        ),
        migrations.AlterModelTable(
            name='empresapessoaview',
            table='SYS_LISTAR_EMPRESA_VI',
        ),
    ]
