# Generated by Django 5.1 on 2024-11-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_alter_horas_trabalhadas_hrt_dt_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='horas_trabalhadas',
            name='HRT_STATUS',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
