# Generated by Django 5.1 on 2024-11-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_rename_emp_objetivo_empresainfo_emp_ramo_atuacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='CLI_CNPJ',
        ),
    ]
