# Generated by Django 5.1 on 2024-11-24 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_sysdetalhestarefasvi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horas_reprovadas',
            name='HRT_COD',
        ),
        migrations.AddField(
            model_name='horas_reprovadas',
            name='TRF_COD',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='plataforma.tarefas'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='sysdetalhestarefasvi',
            table='SYS_DETALHES_TAREFAS_VI',
        ),
    ]
