# Generated by Django 5.1 on 2024-11-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_alter_empresainfo_emp_cod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysGraficosHorasVi',
            fields=[
                ('trf_titulo', models.CharField(max_length=255)),
                ('data_inicio', models.CharField(max_length=10)),
                ('data_fim', models.CharField(max_length=10)),
                ('total_trabalhado', models.TimeField()),
                ('PES_COD_id', models.IntegerField()),
                ('TRF_COD_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SYS_GRAFICOS_HORAS_VI',
                'managed': False,
            },
        ),
    ]
