# Generated by Django 5.1 on 2024-11-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_sysgraficoshorasvi'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='PJT_VLR_HORA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
