# Generated by Django 5.1 on 2024-11-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_projeto_pjt_vlr_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='PJT_OBSERVACAO',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
