# Generated by Django 5.1 on 2024-11-30 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_pessoa_pes_foto_referencia_pessoa_pes_foto_url'),
        ('plataforma', '0009_projeto_pjt_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='EMP_COD',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='login.empresa'),
            preserve_default=False,
        ),
    ]
