# Generated by Django 5.1 on 2024-12-01 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_pessoa_pes_foto_referencia_pessoa_pes_foto_url'),
        ('plataforma', '0011_sysequipevi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa_Pre_cadastro',
            fields=[
                ('PPC_COD_PRE', models.AutoField(primary_key=True, serialize=False)),
                ('PPC_ACCOUNT_ID', models.CharField(max_length=200)),
                ('PPC_TOKEN', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Pessoa_Pre_cadastro',
            },
        ),
        migrations.AlterField(
            model_name='cargo',
            name='EMP_COD',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.empresa'),
        ),
    ]
