# Generated by Django 5.1 on 2024-12-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_pessoa_pre_cadastro_alter_cargo_emp_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='FUN_APROVADO',
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
    ]
