# Generated by Django 5.1 on 2024-12-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_funcionario_fun_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='FUN_TIPO',
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
    ]
