# Generated by Django 5.1 on 2024-12-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_funcionario_fun_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturasPrevistaVI',
            fields=[
                ('data_trabalho', models.DateField(primary_key=True, serialize=False)),
                ('total_horas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganho_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pes_cod', models.BigIntegerField()),
                ('fun_cod', models.BigIntegerField()),
            ],
            options={
                'db_table': 'SYS_FATURAS_PREVISTA_VI',
                'managed': False,
            },
        ),
    ]
