# Generated by Django 5.1 on 2024-12-01 21:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0016_faturasprevistavi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horas_Aprovadas',
            fields=[
                ('HRA_COD', models.AutoField(primary_key=True, serialize=False)),
                ('HRA_DT_ULTIMA', models.DateTimeField(default=django.utils.timezone.now)),
                ('HRA_JUSTIFICATIVA', models.CharField(max_length=200)),
                ('TRF_COD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.tarefas')),
            ],
            options={
                'db_table': 'Horas_Aprovadas',
            },
        ),
    ]
