# Generated by Django 5.1 on 2024-12-02 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_pessoa_pes_foto_referencia'),
        ('plataforma', '0018_remove_horas_aprovadas_hra_justificativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('INV_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DATA_EMISSAO', models.DateTimeField(auto_now_add=True)),
                ('TOTAL_HORAS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TOTAL_VALOR', models.DecimalField(decimal_places=2, max_digits=10)),
                ('STATUS', models.CharField(max_length=10)),
                ('CLI_COD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.cliente')),
                ('EMP_COD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empresa')),
                ('FUN_COD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.funcionario')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
